add_newline = true

format = """
$os\
$directory\
$git_branch\
$git_status\
$git_state\
$git_metrics\
$package\
$python\
$nodejs\
$golang\
$rust\
$cmd_duration\
$fill\
$time\
$line_break\
$character
"""

[os]
disabled = false
style = "bold white"

[os.symbols]
Arch = " "
Ubuntu = " "
Debian = " "
Fedora = " "
NixOS = " "
Windows = "󰍲 "
Macos = "󰀵 "

[directory]
style = "bold cyan"
truncation_length = 0
truncate_to_repo = false
read_only = "󰌾 "
read_only_style = "bold red"
format = "[$path]($style)[$read_only]($read_only_style) "
home_symbol = "󰋜 ~"

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "
truncation_length = 20
truncation_symbol = "…"

[git_status]
style = "bold yellow"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "󰩞 "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "? "
stashed = "󰏗 "
modified = "! "
staged = "+ "
renamed = "» "
deleted = "✘ "

[git_state]
format = '\([$state( $progress_current/$progress_total)](bold yellow)\) '
cherry_pick = "󰘬 CHERRY"
rebase = " REBASE"
merge = "󰘭 MERGE"
revert = " REVERT"
bisect = " BISECT"

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false

[fill]
symbol = " "

[time]
disabled = false
format = "[$time]($style) "
style = "bold dimmed white"
time_format = "%I:%M %p"

[package]
symbol = "󰏗 "
style = "bold yellow"
format = "[$symbol$version]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

[cmd_duration]
min_time = 500
format = "[󱦟 $duration](bold yellow) "

[python]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold blue"

[nodejs]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold green"

[golang]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold cyan"

[rust]
symbol = " "
format = "[$symbol$version]($style) "
style = "bold red"